### ISSUE TITLE
raiden-up fails.  Maybe because virtualenvwrapper.sh is installed somewhere else.

### ISSUE THREAD

**Issue by pirapira** [kelsos/test-environment-scripts#4]
```
(test-scripts) skk% raiden-up -n rinkeby -a 0 -e production -l y                                            (git)-[specify_version]  ~/src/test-environment-scripts
Using RPC endpoint 
using local transport
logs will be stored at /home/yoichi/src/test-environment-scripts/logs/4/production/account1
Starting network rinkeby on configuration production with account account1
Activating virtual enviroment
/home/yoichi/src/test-environment-scripts//raiden-up.sh: line 110: /usr/bin/virtualenvwrapper.sh: No such file or directory
/home/yoichi/src/test-environment-scripts//raiden-up.sh: line 111: workon: command not found
webui should be available shortly at http://localhost:5100
/home/yoichi/src/test-environment-scripts//raiden-up.sh: line 129: raiden: command not found
```

**Comment by pirapira** [comment]
* Maybe the guide should be modified so that the `virtualenvwrapper.sh` is installed in `/usr/bin`.
* Maybe the script should be modified so that it finds the `virtualenvwrapper.sh` from a reasonable location.

@kelsos which sounds more reasonable?

**Comment by kelsos** [comment]
@pirapira I would guess the more reasonable approach would be not to tie the script to virtualenvwrapper at all. I will go on an modify the script so that it can be used with virtualenv too

**Comment by pirapira** [comment]
I'll test the current script.  Thanks.

**Comment by pirapira** [comment]
I still see a similar failure but `pip install virtualenvwrapper` fixes it.  Maybe this should be documented.

**Comment by pirapira** [comment]
Before `pip install virtualenvwrapper` I see
```
/home/yoichi/src/test-environment-scripts//raiden-up.sh: line 110: source: filename argument required
```

**Comment by kelsos** [comment]
OK I will add it as information and I will also try removing virtualenvwrapper from the system to test

**Comment by kelsos** [comment]
@pirapira I also added information about installing `virtualenvwrapper` so it should be safe to close this issue right?
